// Action types for the App context
export const TOGGLE_SIDEBAR = 'TOGGLE_SIDEBAR';
export const SET_SIDEBAR_COLLAPSED = 'SET_SIDEBAR_COLLAPSED';
export const SET_SELECTED_NAVIGATION = 'SET_SELECTED_NAVIGATION';
export const SET_EXPANDED_ITEMS = 'SET_EXPANDED_ITEMS';
export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const ADD_SEARCH_HISTORY = 'ADD_SEARCH_HISTORY';
export const REMOVE_SEARCH_HISTORY = 'REMOVE_SEARCH_HISTORY';
export const CLEAR_SEARCH_HISTORY = 'CLEAR_SEARCH_HISTORY';
export const TOGGLE_THEME = 'TOGGLE_THEME';
export const SET_THEME = 'SET_THEME';
