export const mockRows = [
  { id: 1, name: 'Alice', email: 'alice@example.com', visits: 34 },
  { id: 2, name: 'Bob', email: 'bob@example.com', visits: 21 },
  { id: 3, name: 'Carol', email: 'carol@example.com', visits: 45 },
  { id: 4, name: 'Dan', email: 'dan@example.com', visits: 12 },
  { id: 5, name: 'Eve', email: 'eve@example.com', visits: 27 },
];

export const mockChartData = [
  { date: '2025-10-20', value: 10 },
  { date: '2025-10-21', value: 20 },
  { date: '2025-10-22', value: 12 },
  { date: '2025-10-23', value: 30 },
  { date: '2025-10-24', value: 25 },
  { date: '2025-10-25', value: 40 },
];

export const mockEmployees = [
  {
    id: 1,
    name: 'Sarah Johnson',
    email: 'sarah.j@company.com',
    position: 'Senior Developer',
    department: 'Engineering',
    status: 'Active',
    avatarUrl: 'https://i.pravatar.cc/150?img=1',
    profileUrl: '/employees/1',
  },
  {
    id: 2,
    name: 'Michael Chen',
    email: 'michael.c@company.com',
    position: 'Product Manager',
    department: 'Product',
    status: 'Active',
    avatarUrl: 'https://i.pravatar.cc/150?img=12',
    profileUrl: '/employees/2',
  },
  {
    id: 3,
    name: 'Emily Rodriguez',
    email: 'emily.r@company.com',
    position: 'UX Designer',
    department: 'Design',
    status: 'Active',
    avatarUrl: 'https://i.pravatar.cc/150?img=5',
    profileUrl: '/employees/3',
  },
  {
    id: 4,
    name: 'James Wilson',
    email: 'james.w@company.com',
    position: 'Data Analyst',
    department: 'Analytics',
    status: 'Active',
    avatarUrl: 'https://i.pravatar.cc/150?img=13',
    profileUrl: '/employees/4',
  },
  {
    id: 5,
    name: 'Jessica Brown',
    email: 'jessica.b@company.com',
    position: 'Marketing Lead',
    department: 'Marketing',
    status: 'Active',
    avatarUrl: 'https://i.pravatar.cc/150?img=9',
    profileUrl: '/employees/5',
  },
  {
    id: 6,
    name: 'David Martinez',
    email: 'david.m@company.com',
    position: 'DevOps Engineer',
    department: 'Engineering',
    status: 'Active',
    avatarUrl: 'https://i.pravatar.cc/150?img=14',
    profileUrl: '/employees/6',
  },
  {
    id: 7,
    name: 'Lisa Anderson',
    email: 'lisa.a@company.com',
    position: 'HR Manager',
    department: 'Human Resources',
    status: 'Active',
    avatarUrl: 'https://i.pravatar.cc/150?img=10',
    profileUrl: '/employees/7',
  },
  {
    id: 8,
    name: 'Robert Taylor',
    email: 'robert.t@company.com',
    position: 'Sales Director',
    department: 'Sales',
    status: 'Inactive',
    avatarUrl: 'https://i.pravatar.cc/150?img=15',
    profileUrl: '/employees/8',
  },
];
